#!/bin/sh
# To enable this hook, copy locally this file and move to  ".git/hooks/commit-msg".

export MESSAGE=$(<$1)
export GITHUB_ISSUE_TAG='HELL-([0-9]*)'

if [[ $MESSAGE =~ GITHUB_ISSUE_TAG ]]; then
  echo -e "\e[32mYes! It contains a GitHub issue!\e[0m"
  exit 0;
fi

echo -e "\e[31mOh no... You forgot to add a GitHub issue number!\e[0m";
exit 1;