version: 2.1
jobs:
  deploy:
    working_directory: ~/PiS-Hello
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "Upload server"
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

            gcloud --quiet compute scp --recurse /root/PiS-Hello/server $USER@pis:~/pis

            gcloud --quiet compute ssh $USER@pis --strict-host-key-checking=no --command "cd pis && server/gradlew -b server/build.gradle.kts bootRun"







workflows:
  say-hello-workflow-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - HPIS-41-circleci-gcp