version: 2.1

jobs:
  deploy:
    working_directory: ~/PiS-Hello
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: ls -A1 ~/PiS-Hello
      - run: pwd
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud projects list
          gcloud --quiet compute ssh $USER@pis --strict-host-key-checking=no --command "ls"

          gcloud --quiet compute scp /root/PiS-Hello/README.md krupa_olga00@pis:~/pis_r

          gcloud --quiet --project="${GOOGLE_PROJECT_ID}" compute scp --recurse /root/PiS-Hello/server krupa_olga00@pis:~/pis_server






workflows:
  say-hello-workflow-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - HPIS-41-circleci-gcp