version: 2.1

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud compute os-login ssh-keys add --key=$GCP_KEY

          gcloud compute ssh $USER@pis --command="ls"

workflows:
  say-hello-workflow-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - HPIS-41-circleci-gcp