version: 2.1

jobs:
  deploy:
    working_directory: ~/PiS-Hello
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: ls -A1 ~/PiS-Hello
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud projects list
          gcloud --quiet --project="${GOOGLE_PROJECT_ID}" compute ssh krupa_olga00@pis --zone "${GOOGLE_COMPUTE_ZONE}" --strict-host-key-checking=no --command "ls"

          gcloud \
            --quiet \
            --project="${GOOGLE_PROJECT_ID}" \
            compute ssh krupa_olga00@pis \
            --zone "${GOOGLE_COMPUTE_ZONE}" \
            --strict-host-key-checking=no \
            --command "ls"

          gcloud \
            --quiet \
            --project="${GOOGLE_PROJECT_ID}" \
            compute scp \
            $CIRCLE_WORKING_DIRECTORY/README.md \
            krupa_olga00@pis:~/pis





workflows:
  say-hello-workflow-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - HPIS-41-circleci-gcp