version: 2.1

jobs:
  build:
    docker:
      - image: gradle:jdk11-alpine
    working_directory: /tmp
    steps:
      - run:
          name: Creating  Artifacts
          command: |
              echo "my artifact file" > /tmp/artifact-1;
              mkdir /tmp/artifacts;
              echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - run:
          command: |
            echo "my artifact file on_fail" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir on_fail" > /tmp/artifacts/artifact-2;
          when: on_fail

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

  test:
    docker:
      - image: gradle:jdk11-alpine
    steps:
      - run:
          name: Creating  Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - run:
          name: "Update apt"
          command: "apk add --update openssh-client git sed"
      - checkout
      - run:
          name: "Build project"
          command: "gradle build"
      - run:
          name: "Run tests"
          command: "gradle test"
#      - store_test_results:
#          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  publish:
    docker:
      - image: gradle:jdk11-alpine
    steps:
      - run:
          name: "Update apt"
          command: "apk add --update openssh-client git sed"
      - checkout
      - run:
          name: "Build project"
          command: "gradle build"
      - run:
          name: "Publish a package"
          command: |
            sed -i 's/${ARTIFACTORY_USERNAME}/'${ARTIFACTORY_USERNAME}'/g' gradle.properties
            sed -i 's/${ARTIFACTORY_PASSWORD}/'${ARTIFACTORY_PASSWORD}'/g' gradle.properties
            gradle artifactoryPublish
#      - store_artifacts:
#          path: /tmp/artifacts

workflows:
  say-hello-workflow:
    jobs:
#      - build
      - test
      - publish
