version: 2.1

orbs:
  jira: circleci/jira@1.3.1

jobs:
  test:
    docker:
      - image: gradle:jdk11-alpine
    steps:
      - checkout
      - run:
          name: "Build project"
          command: "gradle build"
      - run:
          name: "Run tests"
          command: "gradle test"
      - jira/notify:
          scan_commit_body: true 
          environment_type: production 
          token_name: JIRA 

workflows:
  say-hello-workflow:
    jobs:
      - test
