version: 2.1

jobs:
  test:
    docker:
      - image: gradle:jdk11-alpine
    steps:
      - run:
          name: "Update apt"
          command: "apk add --update openssh-client git sed"
      - checkout
      - run:
          name: "Build project"
          command: "cd server && gradle build"
      - run:
          name: "Run tests"
          command: "cd server && gradle test"
  publish:
    docker:
      - image: gradle:jdk11-alpine
    steps:
      - run:
          name: "Update apt"
          command: "apk add --update openssh-client git sed"
      - checkout
      - run:
          name: "Build project"
          command: "cd server && gradle build"
      - run:
          name: "Publish a package"
          command: |
            sed -i 's/${ARTIFACTORY_USERNAME}/'${ARTIFACTORY_USERNAME}'/g' server/gradle.properties
            sed -i 's/${ARTIFACTORY_PASSWORD}/'${ARTIFACTORY_PASSWORD}'/g' server/gradle.properties
            cd server && gradle artifactoryPublish

workflows:
  say-hello-workflow:
    jobs:
      - test
      - publish